workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: "3.16.0"
    scripts:
      - name: Force Build with Fix
        script: |
          echo "=== IGNORING ANDROID VERSION WARNINGS ==="
          flutter clean
          flutter pub get
          flutter build apk --release --no-shrink --no-pub
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - vladbogus498@gmail.com