workflows:
  android-workflow:
    name: Android Build
    environment:
      groups:
        - keystore_credentials
    scripts:
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - vladbogus498@gmail.com